[build]
target = "i686-pc-windows-msvc"

[target.i686-pc-windows-msvc]
rustflags = ["-C", "link-args=/MANIFESTUAC:level='asInvoker' /MANIFEST:EMBED"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-args=/MANIFESTUAC:level='asInvoker' /MANIFEST:EMBED"]
